### ISSUE TITLE
Heaviest sound

### ISSUE THREAD

**Issue by pgchamberlin** [Heydon/AMA#2]
What's the heaviest sound and what does it weigh?

**Comment by Heydon** [comment]
This is an excellent question, @pgchamberlin. 

To old-schoolers it is the sound of Black Sabbath, which weighs around 14-15 tins of Tate & Lyle's Golden Syrup. Many of the heavier sounds that have emerged since use the same chemical template. One Dopethrone is approximately equivalent to 72 tupperwares of frozen lasagne, and an (eponymous) Iron Monkey amounts to 6 cheese wheels (Henri Willig gouda), 2 baby deers, and a postage stamp. 

Like cannabis growers contriving stains with ever higher concentrations of THC, musicians are currently engaged in an arms race to create the heaviest possible sound. Recent developments include The Body's "Released From Love / You, Whom I Have Always Hated" which weighs two pregnant pandas (one with twins), and Secret Cutter's "Quantum Eraser" which is _so_ heavy when it goes swimming the whales start singing _We Are Family_.

**Comment by pgchamberlin** [comment]
I think I'd be pleased if I could make a sound even just as heavy as two or three lasagnas. That would do for me. Got to take your hat off to these people. Class acts.
